version: '3.9'
services:
  measurement:
    container_name: measurement
    build:
      context: ./Backend
      dockerfile: MeasurementAPI/Dockerfile
    networks:
        - patient-network         
    ports:
      - "3000:80"
  patientapi:
    container_name: patientapi
    build:
      context: ./Backend
      dockerfile: Patientapi/Dockerfile
    networks:
        - patient-network         
    ports:
      - "3001:80"
  doctor:
    container_name: doctor
    build:
      context: ./Frontend/Doctor/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  patient:
    container_name: patient
    hostname: patient
    build:
      context: ./Frontend/Patient/frontend
      dockerfile: Dockerfile
    networks:
        - patient-network
    ports:
      - "4201:80"
    depends_on:
      - measurement
      
networks:
  patient-network:
    external: true
    driver: bridge
