version: '3.9'
services:
  featurehub:
    container_name: featurehub
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db      
    ports:
      - 8085:8085
    networks:
      - patient-network

  measurement:
    container_name: measurement
    build:
      context: ./Backend
      dockerfile: MeasurementAPI/Dockerfile
    networks:
        - patient-network         
    ports:
      - "3000:80"
    depends_on:
      - featurehub
  patientapi:
    container_name: patientapi
    build:
      context: ./Backend
      dockerfile: Patientapi/Dockerfile
    networks:
        - patient-network         
    ports:
      - "3001:80"
  doctor:
    container_name: doctor
    build:
      context: ./Frontend/Doctor/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  patient:
    container_name: patient
    hostname: patient
    build:
      context: ./Frontend/Patient/frontend
      dockerfile: Dockerfile
    networks:
        - patient-network
    ports:
      - "4201:80"
    depends_on:
      - measurement

volumes:
  featurehub-h2-data:
      
networks:
  patient-network:
    external: true
    driver: bridge
