version: '3.9'
services:
  measurement:
    container_name: measurement
    build:
      dockerfile: Backend/MeasurementAPI/Dockerfile
      context: .
    ports:
      - "3000:80"
  doctor:
    container_name: doctor
    build:
      context: ./Frontend/Doctor/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  patient:
    container_name: patient
    build:
      context: ./Frontend/Patient/frontend
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - measurement
