version: '3.9'
services:
  hageman:
    build:
      context: ./Frontend/Doctor/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  janning:
    build:
      context: ./Frontend/Patient/frontend
      dockerfile: Dockerfile
    ports:
      - "4201:80"