name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Echo Docker Hub secrets
        run: |
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}"
          echo ls
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Test
        id: Test
        run: dotnet test --no-build ~/Backend/test1/test1.csproj
        
          
        
      - name: Build and push measurement backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/MeasurementAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/measurement:latest
        
      - name: Build and push patient backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/PatientAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/patient:latest
                  
      - name: Build and push patient frondend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend/Patient/frontend
          file: ./Frontend/Patient/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/patientfrondend:latest
                  
      - name: Build and push doctor frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend/Doctor/frontend
          file: ./Frontend/Doctor/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/doctorfrontend:latest
      
