name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Docker Hub secrets
        run: |
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push measurement backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Backend/MeasurementAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/measurement:latest
        
      - name: Build and push patient backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Backend/PatientAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/patient:latest
                  
      - name: Build and push patient frondend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Frontend/patient/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/patientfrondend:latest
                  
      - name: Build and push doctor frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Frontend/doctor/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/doctorfrontend:latest
      
